# -*- coding: utf-8 -*-
"""sentence Transformers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vFFLEPR4yxhEfOgBndt5JqwmbPEMqiRS
"""



! pip install Sentence_Transformers
from sentence_transformers import SentenceTransformer,util
#load the model
model=SentenceTransformer('all-miniLM-L6-V2')
#take input from user
text1=input("enter text 1: ")
text2=input("enter text 2: ")
# convert text to embeddings
embedding1=model.encode(text1)
embedding2=model.encode(text2)
#calculate similarity
similarity=util.cos_sim(embedding1,embedding2)
#show result
print("\n similarity score : ",round (float(similarity),2))
if similarity > 0.75:
  print("similarity level: high")
elif similarity > 0.4:
  print("similarity level: medium")
else:
  print("similarity level: low")

