# -*- coding: utf-8 -*-
"""text generation transformers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tiqDZe6us9UDsVct5I22wAD48pDucdKP
"""



! pip install transformer table

from transformers import pipeline
# load text generation model(gen AI)
generator = pipeline(
    "text-generation",
    model = "gpt2"
)
# input prompt
prompt = "Artifical Intelligence in finance will"
# generate text
result = generator(prompt,max_length=50,num_return_sequences=1)
print("AI Generated Text:")
print(result [0]['generated_text'])