# -*- coding: utf-8 -*-
"""Torch Pandas transformers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h373ERqEYMw-KbMwTlE2AFQVLnLBVoTV
"""

!pip installtransformers torch pandas
from transformers import pipeline
import pandas as pd
#load sentiment analysis model
sentiment = pipeline ("sentiment-analysis")
#sample product review( you can change only this text later)
reviews=""" the laptop starts quickly and works smoothly for daily tasks.
            the screen quality is clear and good for watching videos.
            battery backup is average and needs charging often.
            the fan makesnoise when many apps are running.
            overall,it is a good laptop for student but not for gaming."""
#split review into sentences
sentences = reviews.split(",")
pros = []
cons = []
for S in sentences:
  S = S.strip()
  if S==" ":
     continue
result = sentiment(S)[0]
if result ["label"] =="POSITIVE":
     pros.append(S)
elif result ["label"] =="NEGATIVE":
  cons.append(S)
#take only 2 poros and 2 cons
pros =pros[:2]
cons =cons[:2]
#create table
df =pd.DataFrame({
    "pros" : pros,
    "cons" : cons
})
df